name: 1.Build MiniOS LXFce Trixie Noble Resolute SiD (Parallel)
on:
  workflow_dispatch:

env:
  TZ: Etc/GMT-7

jobs:
  build-trixie:
    name: Build Trixie Edition
    runs-on: ubuntu-24.04
    timeout-minutes: 600
    steps:
      - name: Prepare | Get Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Prepare | Initialize & Install Dependencies
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E systemctl daemon-reload
          sudo -E apt-get clean
          sudo -E timedatectl set-timezone "${TZ:-Etc/GMT-7}"
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Create Virtual Disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Download and Decompress Build Files
        working-directory: /builder
        run: |
          wget -q https://github.com/1compk/minios/releases/download/live/zMiniOS.SkyLine.Build.05.2026.tar.xz
          tar -xf zMiniOS.SkyLine.Build.05.2026.tar.xz

      - name: Build | Trixie
        working-directory: /builder/zMiniOS.SkyLine.Build.05.2026
        run: |
          sudo apt install binutils debootstrap squashfs-tools xz-utils lz4 zstd xorriso mtools rsync grub-efi-amd64-bin grub-pc-bin grub-common -y
          sudo -E ./minios-cmd -d trixie -a amd64 -de xfce -pv standard -c zstd -l en_US -tz "Etc/GMT-7" -kl -ib dracut

      - name: Upload | Trixie ISO
        uses: actions/upload-artifact@v7
        with:
          name: MiniOS-Trixie-ISO-${{ steps.date.outputs.DATE }}
          path: /builder/zMiniOS.SkyLine.Build.05.2026/build/iso/*.iso
          archive: false
          if-no-files-found: error
          retention-days: 30

  build-noble:
    name: Build Noble Edition
    runs-on: ubuntu-24.04
    timeout-minutes: 600
    steps:
      - name: Prepare | Get Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Prepare | Initialize & Install Dependencies
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E systemctl daemon-reload
          sudo -E apt-get clean
          sudo -E timedatectl set-timezone "${TZ:-Etc/GMT-7}"
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Create Virtual Disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Download and Decompress Build Files
        working-directory: /builder
        run: |
          wget -q https://github.com/1compk/minios/releases/download/live/zMiniOS.SkyLine.Build.05.2026.tar.xz
          tar -xf zMiniOS.SkyLine.Build.05.2026.tar.xz

      - name: Build | Noble
        working-directory: /builder/zMiniOS.SkyLine.Build.05.2026
        run: |
          sudo apt install binutils debootstrap squashfs-tools xz-utils lz4 zstd xorriso mtools rsync grub-efi-amd64-bin grub-pc-bin grub-common -y
          sudo -E ./minios-cmd -d noble -a amd64 -de xfce -pv standard -c zstd -l en_US -tz "Etc/GMT-7" -kl -ib dracut

      - name: Upload | Noble ISO
        uses: actions/upload-artifact@v7
        with:
          name: MiniOS-Noble-ISO-${{ steps.date.outputs.DATE }}
          path: /builder/zMiniOS.SkyLine.Build.05.2026/build/iso/*.iso
          archive: false
          if-no-files-found: error
          retention-days: 30

  build-resolute:
    name: Build Resolute Edition
    runs-on: ubuntu-24.04
    timeout-minutes: 600
    steps:
      - name: Prepare | Get Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Prepare | Initialize & Install Dependencies
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E systemctl daemon-reload
          sudo -E apt-get clean
          sudo -E timedatectl set-timezone "${TZ:-Etc/GMT-7}"
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Create Virtual Disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Download and Decompress Build Files
        working-directory: /builder
        run: |
          wget -q https://github.com/1compk/minios/releases/download/live/zMiniOS.SkyLine.Build.05.2026.tar.xz
          tar -xf zMiniOS.SkyLine.Build.05.2026.tar.xz

      - name: Build | Resolute
        working-directory: /builder/zMiniOS.SkyLine.Build.05.2026
        run: |
          sudo apt install binutils debootstrap squashfs-tools xz-utils lz4 zstd xorriso mtools rsync grub-efi-amd64-bin grub-pc-bin grub-common -y
          sudo -E ./minios-cmd -d resolute -a amd64 -de xfce -pv standard -c zstd -l en_US -tz "Etc/GMT-7" -kl -ib dracut

      - name: Upload | Resolute ISO
        uses: actions/upload-artifact@v7
        with:
          name: MiniOS-Resolute-ISO-${{ steps.date.outputs.DATE }}
          path: /builder/zMiniOS.SkyLine.Build.05.2026/build/iso/*.iso
          archive: false
          if-no-files-found: error
          retention-days: 30

  build-sid:
    name: Build SiD Edition
    runs-on: ubuntu-24.04
    timeout-minutes: 600
    steps:
      - name: Prepare | Get Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Prepare | Initialize & Install Dependencies
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E systemctl daemon-reload
          sudo -E apt-get clean
          sudo -E timedatectl set-timezone "${TZ:-Etc/GMT-7}"
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Create Virtual Disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare | Download and Decompress Build Files
        working-directory: /builder
        run: |
          wget -q https://github.com/1compk/minios/releases/download/live/zMinios.Skyline.Build.04.2026.tar.xz
          tar -xf zMinios.Skyline.Build.04.2026.tar.xz

      - name: Build | SiD
        working-directory: /builder/zMinios.Skyline.Build.04.2026
        run: |
          sudo apt install binutils debootstrap squashfs-tools xz-utils lz4 zstd xorriso mtools rsync grub-efi-amd64-bin grub-pc-bin grub-common -y
          sudo sh sid.xfce.build.sh

      - name: Upload | SiD ISO
        uses: actions/upload-artifact@v7
        with:
          name: MiniOS-SiD-ISO-${{ steps.date.outputs.DATE }}
          path: /builder/zMinios.Skyline.Build.04.2026/build/iso/*.iso
          archive: false
          if-no-files-found: error
          retention-days: 30