name: 1. MiniOS LXFice Trixie Noble Resolute Sid

on:
  schedule:
    - cron: '0 0 */5 * *' # Run every 5 Days
  workflow_dispatch:

env:
  TZ: Etc/GMT-7
  iMageSize: 120GiB
  MainDir: /builder

  MiniOSBuild: zMiniOS.SkyLine.Build.05.2026.tar.xz
  MiniOSBuildDir: zMiniOS.SkyLine.Build.05.2026

jobs:
  build:
    name: MiniOS ${{ matrix.release }}
    runs-on: ubuntu-24.04
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        include:
          - { release: trixie, Custom: false }
          - { release: noble, Custom: false }
          - { release: resolute, Custom: false }
          - { release: sid, Custom: false }

    steps:
      - name: Prepare | Init & LVM
        run: |
          sudo timedatectl set-timezone "${TZ}"
          sudo swapoff -a || true
          #sudo apt-get update
          sudo apt-get install -y debootstrap squashfs-tools xz-utils xorriso \
            mtools rsync grub-common e2fsprogs lvm2 pv wget btrfs-progs
          
          sudo truncate -s $iMageSize /mnt.img
          sudo truncate -s $iMageSize /root.img
          Loop1=$(sudo losetup --find --show /mnt.img)
          Loop2=$(sudo losetup --find --show /root.img)
          sudo pvcreate $Loop1 $Loop2
          sudo vgcreate github $Loop1 $Loop2
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 /dev/github/runner

          sudo mkdir -p $MainDir
          sudo mount /dev/github/runner $MainDir
          sudo chown -R runner:runner $MainDir
          df -Th

      - name: Prepare | Source Code
        working-directory: /builder
        run: |
          wget -q "https://github.com/1compk/minios/releases/download/live/${{ env.MiniOSBuild }}"
          tar -xf "${{ env.MiniOSBuild }}"

      - name: Build | Run
        working-directory: /builder/${{ env.MiniOSBuildDir }}
        run: |
           sudo -E ./minios-cmd -d ${{ matrix.release }} -a amd64 -de xfce -pv standard -c zstd -l en_US -tz "${TZ}" -kl -ib dracut

      - name: Upload | ISO
        uses: actions/upload-artifact@v7
        with:
          name: MiniOS-${{ matrix.release }}-${{ github.run_id }}
          path: /builder/${{ env.MiniOSBuildDir }}/build/iso/*.iso
          retention-days: 30
          archive: false
          if-no-files-found: error
