name: 6.Build Armbian LXFce Trixie Uefi-x86
on:
  workflow_dispatch:

env:
  TZ: Etc/GMT-7

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 600
    steps:
      - name: Get Current Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/share/boost
          sudo docker image prune -a -f
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y 7zip curl git wget ca-certificates binutils debootstrap \
            squashfs-tools xz-utils lz4 zstd xorriso mtools rsync lvm2 \
            qemu-user-static binfmt-support debian-archive-keyring xfsprogs \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu build-essential \
            udev kmod python3 python3-setuptools systemd-container

      - name: Create virtual disk for extended storage
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Download and Decompress Source
        working-directory: /builder
        run: |
          git clone --depth 1 https://github.com/1compk/armbian.build.git armbian

      - name: Build Armbian
        working-directory: /builder/armbian
        run: |
          chmod +x compile.sh
          ./compile.sh build BOARD=uefi-x86 BRANCH=edge RELEASE=trixie \
           EXPERT=yes BUILD_DESKTOP=yes BUILD_MINIMAL=no \
           DESKTOP_APPGROUPS_SELECTED= DESKTOP_ENVIRONMENT=xfce \
           DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
           KERNEL_BTF=no KERNEL_CONFIGURE=no KERNEL_GIT=shallow \
           DOCKER_ARMBIAN=no SKIP_BOOTSTRAP_SIGNATURE=yes \
           INSTALL_GPG_FIX=yes INSTALL_GRAPHICS_DRIVERS=no
           
      - name: Upload Armbian.iMG
        uses: actions/upload-artifact@v7
        with:
          name: Armbian.LXFce.Trixie.Aml-S9xx-${{ steps.date.outputs.DATE }}
          path: /builder/armbian/output/images/*.img
          archive: true
          if-no-files-found: error
          retention-days: 90
