./compile.sh EXPERT=yes BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no BOARD=uefi-x86 BRANCH=current RELEASE=bookworm

./compile.sh EXPERT=yes BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no BOARD=uefi-x86 BRANCH=edge RELEASE=bookworm

./compile.sh EXPERT=yes BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no BOARD=uefi-x86 BRANCH=current RELEASE=trixie

./compile.sh EXPERT=yes BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no BOARD=uefi-x86 BRANCH=edge RELEASE=trixie

./compile.sh EXPERT=yes BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no BOARD=uefi-x86 BRANCH=current RELEASE=jammy

./compile.sh EXPERT=yes BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no BOARD=uefi-x86 BRANCH=edge RELEASE=jammy

./compile.sh EXPERT=yes BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no BOARD=uefi-x86 BRANCH=current RELEASE=noble

./compile.sh EXPERT=yes BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no BOARD=uefi-x86 BRANCH=edge RELEASE=noble
