name: 1. MiniOS LXFice Trixie Noble Resolute Sid

on:
  schedule:
    - cron: '0 0 */5 * *' # Run every 5 Days
  workflow_dispatch:

env:
  TZ: Etc/GMT-7
  IMAGE_SIZE: 100GiB
  BUILDER_DIR: /builder

  BuildFile: zMiniOS.SkyLine.Build.05.2026.tar.xz
  BuildDir: zMiniOS.SkyLine.Build.05.2026

jobs:
  build:
    name: MiniOS ${{ matrix.release }}
    runs-on: ubuntu-24.04
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        include:
          - { release: trixie, is_custom: false }
          - { release: noble, is_custom: false }
          - { release: resolute, is_custom: false }
          - { release: sid, is_custom: false }

    steps:
      - name: Prepare | Init & LVM
        run: |
          sudo timedatectl set-timezone "${TZ}"
          sudo swapoff -a || true
          #sudo apt-get update
          sudo apt-get install -y debootstrap squashfs-tools xz-utils xorriso \
            mtools rsync grub-common e2fsprogs lvm2 pv wget btrfs-progs
          
          sudo truncate -s $IMAGE_SIZE /mnt.img
          sudo truncate -s $IMAGE_SIZE /root.img
          LOOP1=$(sudo losetup --find --show /mnt.img)
          LOOP2=$(sudo losetup --find --show /root.img)
          sudo pvcreate $LOOP1 $LOOP2
          sudo vgcreate github $LOOP1 $LOOP2
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.btrfs -fv /dev/github/runner

          sudo mkdir -p $BUILDER_DIR
          sudo mount /dev/github/runner $BUILDER_DIR
          sudo chown -R runner:runner $BUILDER_DIR
          df -Th

      - name: Prepare | Download
        working-directory: /builder
        run: |
          wget -q "https://github.com/1compk/minios/releases/download/live/${{ env.BuildFile }}"
          tar -xf "${{ env.BuildFile }}"

      - name: Build | Run
        working-directory: /builder/${{ env.BuildDir }}
        run: |
            sudo -E ./minios-cmd -d ${{ matrix.release }} -a amd64 -de xfce -pv standard -c zstd -l en_US -tz "${TZ}" -kl -ib dracut

      - name: Upload | ISO
        uses: actions/upload-artifact@v7
        with:
          name: MiniOS-${{ matrix.release }}-${{ github.run_id }}
          path: /builder/${{ env.BuildDir }}/build/iso/*.iso
          retention-days: 30
          archive: false
          if-no-files-found: error
