name: 2. Armbian Build Forky Trixie CLi LXFice Aml-S9xx Uefi-x86

on:
  schedule:
    - cron: '0 0 */5 * *' # Run every 5 Days
  workflow_dispatch:

env:
  TZ: Etc/GMT-7
  iMageSize: 100GiB
  MainDir: /builder

  BuildFile: zArmbian.Build.05.26.tar.xz
  BuildDir: zArmbian.Build.05.26
  UefiVersion: 26.5.1
  BoxVersion: 26.8.0-trunk.53

jobs:
  build:
    name: Armbian-${{ matrix.board }}-${{ matrix.release }}-${{ matrix.type }}
    runs-on: ${{ matrix.board == 'uefi-x86' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        release: [forky, trixie, resolute]
        board: [aml-s9xx-box, uefi-x86]
        type: [CLi, LXFice]

        exclude:
          # ===== (No CLi) =====
          - board: aml-s9xx-box
            type: CLi

          # ===== (No LXFice) =====
          - release: trixie
            type: LXFice
          - release: resolute
            type: LXFice

        include:
          # ===== (Build CLi) =====
          - type: CLi
            desktop: no
            environment: ""
            config_name: ""
            revision: 26.8.0-trunk.53

          # ===== (Build LXFice) =====
          - type: LXFice
            desktop: yes
            environment: xfce
            config_name: config_base
            revision: 26.2.0-trunk.844

    steps:
      - name: Prepare | Init & LVM
        run: |
          sudo timedatectl set-timezone "${TZ}"
          sudo swapoff -a || true
          sudo apt-get update
          sudo apt-get install -y debootstrap squashfs-tools xz-utils xorriso \
            mtools rsync grub-common e2fsprogs lvm2 pv wget btrfs-progs
          
          sudo truncate -s $iMageSize /mnt.img
          sudo truncate -s $iMageSize /root.img
          Loop1=$(sudo losetup --find --show /mnt.img)
          Loop2=$(sudo losetup --find --show /root.img)
          sudo pvcreate $Loop1 $Loop2
          sudo vgcreate github $Loop1 $Loop2
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 /dev/github/runner

          sudo mkdir -p $MainDir
          sudo mount /dev/github/runner $MainDir
          sudo chown -R runner:runner $MainDir
          df -Th

      - name: Prepare | Source Code
        working-directory: /builder
        run: |
          git clone --depth 3 https://github.com/armbian/build.git ${{ env.BuildDir }}
          cd ${{ env.BuildDir }}
          git fetch --all --tags
          
          if [ "${{ matrix.desktop }}" = "yes" ]; then
            git checkout --detach v26.2.0-trunk.844
            
            PackagesDir="config/desktop/${{ matrix.release }}/environments/xfce/config_base"
            mkdir -p $PackagesDir
            cd $PackagesDir
            
            rm -rf packages
            wget -q "https://github.com/1compk/dl/raw/dl/xfce/packages"
          else
            git checkout --detach v26.8.0-trunk.53
          fi

      - name: Build | Run
        working-directory: /builder/${{ env.BuildDir }}
        run: |
          if [ "${{ matrix.board }}" = "uefi-x86" ]; then
            SetVersion="${{ env.UefiVersion }}"
          else
            SetVersion="${{ env.BoxVersion }}"
          fi

          chmod +x compile.sh
          ./compile.sh build \
            EXPERT=yes \
            BOARD=${{ matrix.board }} \
            BRANCH=edge \
            RELEASE=${{ matrix.release }} \
            BUILD_DESKTOP=${{ matrix.desktop }} \
            BUILD_MINIMAL=no \
            DESKTOP_APPGROUPS_SELECTED= \
            DESKTOP_ENVIRONMENT="${{ matrix.environment }}" \
            DESKTOP_ENVIRONMENT_CONFIG_NAME="${{ matrix.config_name }}" \
            KERNEL_BTF=no \
            KERNEL_CONFIGURE=no \
            KERNEL_GIT=shallow \
            DOCKER_ARMBIAN=no \
            BUILD_AUTO_UPDATE=no \
            IMAGE_VERSION="$SetVersion" \
            REVISION="$SetVersion" \
            INSTALL_NVIDIA_DRIVERS=no

      - name: Upload | Image
        uses: actions/upload-artifact@v7
        with:
          name: Armbian-${{ matrix.board }}-${{ matrix.release }}-${{ matrix.type }}-${{ github.run_id }}
          path: /builder/${{ env.BuildDir }}/output/images/*.img*
          retention-days: 30
          archive: true
          if-no-files-found: error
