name: 6.Build Armbian LXFce Trixie Uefi-x86
on:
  workflow_dispatch:

env:
  TZ: Etc/GMT-7

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      date: ${{ steps.date.outputs.DATE }}
    steps:
      - name: Get Current Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Free Disk Space (Host)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/share/boost
          sudo docker image prune -a -f

  build:
    needs: prepare
    runs-on: ubuntu-24.04
    timeout-minutes: 600
    container:
      image: debian:trixie
      options: --privileged --device /dev/loop-control:/dev/loop-control
    steps:
      - name: Install Base Essentials
        run: |
          apt-get update
          apt-get install -y sudo kmod udev

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y 7zip curl git wget ca-certificates binutils debootstrap \
            squashfs-tools xz-utils lz4 zstd xorriso mtools rsync lvm2 \
            qemu-user-static binfmt-support debian-archive-keyring xfsprogs \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu build-essential \
            udev kmod python3 python3-setuptools systemd-container

      - name: Create virtual disk for extended storage
        run: |
          for i in $(seq 0 7); do
            [ -b /dev/loop$i ] || sudo mknod -m 0660 /dev/loop$i b 7 $i
          done

          mnt_free_mb=$(df -m /mnt | awk 'NR==2 {print $4}')
          root_free_mb=$(df -m / | awk 'NR==2 {print $4}')
          mnt_size_mb=$((mnt_free_mb - 2048))
          root_size_mb=$((root_free_mb - 4096))
          
          sudo truncate -s "${mnt_size_mb}"M /mnt/mnt.img
          sudo truncate -s "${root_size_mb}"M /root.img
          
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          
          sudo pvcreate -y /dev/loop6 /dev/loop7
          sudo vgcreate -y github /dev/loop6 /dev/loop7

          sudo lvcreate -y -n runner -l 100%FREE github --noudevsync

          sudo vgscan --mknodes
          sudo vgchange -ay
          
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/mapper/github-runner
          
          sudo mkdir -p /builder
          sudo mount /dev/mapper/github-runner /builder
          sudo chown -R root:root /builder
          df -Th

      - name: Download Armbian Source
        working-directory: /builder
        run: |
          git clone --depth 1 https://github.com/1compk/armbian.build.git armbian

      - name: Build Armbian
        working-directory: /builder/armbian
        run: |
          chmod +x compile.sh
          ./compile.sh build BOARD=uefi-x86 BRANCH=edge RELEASE=trixie \
           EXPERT=yes BUILD_DESKTOP=yes BUILD_MINIMAL=no \
           DESKTOP_APPGROUPS_SELECTED= DESKTOP_ENVIRONMENT=xfce \
           DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
           KERNEL_BTF=no KERNEL_CONFIGURE=no KERNEL_GIT=shallow \
           DOCKER_ARMBIAN=no

      - name: Upload Armbian.iMG
        uses: actions/upload-artifact@v4
        with:
          name: Armbian.LXFce.Trixie.Uefi-x86-${{ needs.prepare.outputs.date }}
          path: /builder/armbian/output/images/*.img
          if-no-files-found: error
          retention-days: 90
